stages:
  - test

golang-test:
  stage: test
  image: golang:1.19-alpine
  script:
    - go install gotest.tools/gotestsum@latest
    - gotestsum --junitfile report.xml --format testing-all ./services.boilerplate/... ./services.shared/...
  artifacts:
    when: always
    reports:
      junit: report.xml