stages:
  - test

variables:
  CGO_ENABLED: 0

install-dependencies:
  stage: test
  image: golang:1.19-alpine
  script:
    - go mod download
    - go mod verify

golang-test:
  stage: test
  image: golang:1.19-alpine
  script:
    - go install gotest.tools/gotestsum@latest
    - gotestsum --junitfile report.xml --format testname ./services.boilerplate/... ./services.shared/...
  artifacts:
    when: always
    reports:
      junit: report.xml