stages:
  - lint
  - test

variables:
  CGO_ENABLED: 0

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - go.mod
    - go.sum

lint-golang:
  stage: lint
  image: golang:1.19-alpine
  script:
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - golangci-lint run --out-format=checkstyle --out=report.xml ./services.boilerplate/... ./services.shared/...

golang-test:
  stage: test
  image: golang:1.19-alpine
  script:
    - go install gotest.tools/gotestsum@latest
    - gotestsum --junitfile report.xml --format testname ./services.boilerplate/... ./services.shared/...
  artifacts:
    when: always
    reports:
      junit: report.xml